### ISSUE TITLE
Settings for multipe GPUs

### ISSUE THREAD

**Issue by jmakov** [WickedLukas/nvidia-tuner#4]
Thanks for sharing, it just works!
Is there a way to set e.g. fan speeds for multiple gpus? As far as I understand, only 1 GPU can be set at a time (via the `--index` flag). When run as a service, can all GPUs be configured or would every GPU require it's own service?

Also sometimes ctrl+c doesn't exit the process, it just hangs.

**Comment by WickedLukas** [comment]
Hi, you are right. Just make a service for each GPU instead. Then you can also set individual and better optimized settings.

For me ctrl-c works reliably printing that the default fan speeds were set. Did you try `pkill -SIGINT nvidia-tuner`
instead, which should stop the program the same way? It would also be interesting if `pkill -SIGTERM nvidia-tuner`
works better.
