### ISSUE TITLE
Failed to initialize NVML

### ISSUE THREAD

**Issue by jmakov** [WickedLukas/nvidia-tuner#5]
Ubuntu 24.10

$ ./target/release/nvidia-tuner --index 0 --pairs 30:100 
thread 'main' panicked at src/main.rs:23:86:
called `Result::unwrap()` on an `Err` value: "Failed to initialize NVML: a libloading error occurred: libnvidia-ml.so: cannot open shared object file: No such file or directory"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

This solved the issue for me: 
`sudo ln -s /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so`

**Comment by WickedLukas** [comment]
Did you try to reinstall your driver? Although it seems to work now, it sounds more like a workaround.

**Comment by jmakov** [comment]
This is a fresh install of Ubuntu Server 24.10 with `apt instal nvidia-utils-560 nvidia-driver-560`.

**Comment by WickedLukas** [comment]
Well, I am using Endeavour OS and those links exist by default. I did some google search and found people having issues with this file missing when using Nvidias own nvidia-smi, so this must be something unrelated to my tool. Also, since you made it work, I close this topic.
