### ISSUE TITLE
Service doesn't start on headless server

### ISSUE THREAD

**Issue by jmakov** [WickedLukas/nvidia-tuner#6]
Running `sudo systemctl start nvidia-tuner-gpu0.service` on a headless server just blocks and doesn't finish until interrupted (ctrl+c). Config:
```shell
[Unit]
Description=nvidia-tuner-gpu0
After=graphical.target

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/nvidia-tuner --index 0 --pairs 30:100
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=graphical.target
```
built with `cargo build --release`

**Comment by WickedLukas** [comment]
Hi, since you are running it on a headless server you should replace the „graphical.target“ with „ multi-user.target“.

**Comment by jmakov** [comment]
Thanks for the quick response. Running `sudo systemctl start nvidia-tuner-gpu0.service` I can hear the fans spin up, but the command is blocking - I need to press ctrl+c to get back to the shell.

**Comment by WickedLukas** [comment]
I am no systemd expert. I think the „After“ Part might be redundant, so you can try to leave it out. Also I am wondering why you build the tool yourself instead of just using my latest release.

**Comment by jmakov** [comment]
> Also I am wondering why you build the tool yourself instead of just using my latest release.

Don't know under what name the package lives in Ubuntu repos. So just went with `cargo build --release`.

> I am no systemd expert. I think the „After“ Part might be redundant, so you can try to leave it out.

This works for me:
```
[Unit]
Description=nvidia-tuner-gpu1

[Service]
ExecStart=/usr/local/sbin/nvidia-tuner --index 1 --pairs 30:100
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
```
